name: CD Pipeline

on:
    workflow_run:
        workflows: ["CI Pipeline"]  
        types:
            - completed
  
jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Pull Docker Image
      run: sudo docker pull youngprinnce/cicd-pipeline:latest

    - name: Delete Docker Container
      run: sudo docker rm -f cicd-pipeline || true
    
    - name: Run Docker Container
      run: sudo docker run -d -p 8080:8080 --name cicd-pipeline youngprinnce/cicd-pipeline:latest
