name: CD Pipeline

on:
    workflow_run:
        workflows: ["CI Pipeline"]  
        types:
            - completed
  
jobs:

  deploy:

    runs-on: self-hosted

    steps:
    - name: Pull Docker Image
      run: sudo docker pull youngprinnce/cicd-pipeline:latest

    - name: Stop and Remove Old Docker Container
      run: |
        sudo docker stop cicd-pipeline || true
        sudo docker rm cicd-pipeline || true
    
    - name: Run Docker Container
      run: sudo docker run -d -p 8080:8080 --name cicd-pipeline youngprinnce/cicd-pipeline:latest
